#!/usr/bin/env bash
# Copyright (c) 2021 Yang, Yun-Tse (Acer.Yang). All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
base_dir=$(dirname "$0")
PATH=$PATH:$base_dir
PYTHONDONTWRITEBYTECODE=1 exec python "$base_dir/agg.py" "$@"
